### ISSUE TITLE
Buttons change their sizes in different states

### ISSUE THREAD

**Issue by andrii-codefresh** [argoproj/argo-ui#126]
**Describe the bug**

Buttons change their sizes in different states (focus, hover, etc.). It causes element jumping during interaction with buttons.
Like mentioned in this issue: https://github.com/argoproj/argo-cd/issues/6946

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications/argo-cd?view=pods&orphaned=false
2. Press the ‘APP DETAILS’ button several times

**Expected behavior**

Buttons keep their size and don’t move each other and other content.

**Screenshots**

https://user-images.githubusercontent.com/41997149/129383573-90e81d79-8aa9-4e0d-9c08-ceb02de93af6.mp4

**Comment by rbreeze** [comment]
Hi @andrii-codefresh, 

This has been addressed with a new component introduced in `argo-ui/v2` called `ActionButton`. We're slowly migrating the interfaces in Argo CD to use the new components.
