### ISSUE TITLE
Workflows list: item line misbehaves when the message is too long

### ISSUE THREAD

**Issue by vidarlx** [argoproj/argo-ui#162]
If there is a long message outputed as a workflow run result, the item doesn't look so good.

![image](https://user-images.githubusercontent.com/2722691/139042760-9768f778-58be-498c-870b-c7cea0026581.png)

![image](https://user-images.githubusercontent.com/2722691/139042866-e41be3d4-7462-4c04-9d56-536e9c9626e2.png)

When I changed the message to something short, it looks good 

![image](https://user-images.githubusercontent.com/2722691/139043212-39ec1212-91c8-43eb-8e88-726c89b4f6df.png)

**Comment by agilgur5** [comment]
I fixed this in https://github.com/argoproj/argo-workflows/pull/11908.

For reference, this is a repo for shared components between Argo CD and Argo Workflows, so this issue was filed in the wrong repo -- it should have been filed in Argo Workflows.
