### ISSUE TITLE
Overflow(z-index) [Refreshig...]

### ISSUE THREAD

**Issue by tebaly** [argoproj/argo-ui#173]
![Screenshot (1)](https://user-images.githubusercontent.com/9466814/148024551-2ba16692-4d5c-4cd0-85da-07db7fb4155a.png)

May be wrong

**Comment by agilgur5** [comment]
This looks Argo CD specific. This repo is for common UI components that are shared between CD, Workflows, and Rollouts.

Please re-file in Argo CD's repo if this is still an issue
