### ISSUE TITLE
CVEs introduced via portable-fetch

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-ui#181]
Two CVEs are introduced via the portable-fetch dependency because of its dependency on node-fetch:
* https://app.snyk.io/org/argoproj/project/e257be49-1bf5-455e-a11b-cdab3dbef067#issue-SNYK-JS-NODEFETCH-2342118
* https://app.snyk.io/org/argoproj/project/e257be49-1bf5-455e-a11b-cdab3dbef067#issue-SNYK-JS-NODEFETCH-674311

I don't see any references in argo-ui to `fetch(`, which I think is the function this package introduces.

It looks like the package hasn't been updated for five years. So even if we need it, we should probably look for an alternative.

Can we just remove this dependency since it doesn't appear to be used? If not, can we use an alternative?

**Comment by alexec** [comment]
If it in not used, remove it.

**Comment by agilgur5** [comment]
Fixed by #182
