### ISSUE TITLE
ArgoCD UI: Provide way to change color based on argocd-cm configmap

### ISSUE THREAD

**Issue by nikhleshgoenka** [argoproj/argo-ui#193]
Please provide a way to change the color of argocd-ui by adding the colors in argocd-cm configmap rather than using it from custom CCS

{
    "Version": "v2.4.0+655be25",
    "BuildDate": "2022-04-15T00:29:43Z",
    "GitCommit": "655be25f871d109a7f346c84bf985b397aa87fd9",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.1",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.4.1 2021-11-11T23:36:27Z",
    "HelmVersion": "v3.8.1+g5cb9af4",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}

**Comment by saumeya** [comment]
Hi @nikhleshgoenka this feature does exist - https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/ . I also wrote a [short blog](https://saumeya.github.io/4.custom-styles-argocd.html) about it

**Comment by nikhleshgoenka** [comment]
Thanks, @saumeya I've checked this before and was looking for a direct way without mounting the CCS to avoid any unknown issue during the ArgoCD upgrade. But going through your blog, let me give it a try once and see how it goes :)

**Comment by saumeya** [comment]
Oh, I understand now - it would be tough to customize directly in the config map. You can look at the thread in this issue, where one user is using stylish - https://github.com/argoproj/argo-cd/issues/4722 . Maybe that helps too.
