### ISSUE TITLE
local workflow using yalc

### ISSUE THREAD

**Issue by gaurav5430** [argoproj/argo-ui#220]
Planning to add some documentation around using yalc. Need to confirm a few things and then I can raise a PR

do we need to publish the argo-ui repo after every change that we want reflected?
do we need to `yalc add` on the main (argo-workflows) repo after every change?

it happens sometimes that the already running webpack dev server does not pick up the change even though node_modules are updated. It seems to use the one in memory. Any pointers on how to fix this ?

**Comment by saumeya** [comment]
Hi @gaurav5430 yes looks like we need to run `yalc publish` and `yalc add argo-ui` everytime a change is made. I also realized while working on my last PR. 
Not the best dev experience, but don't know if there is a solution around it.
