### ISSUE TITLE
Helm icon is not being rendered correctly

### ISSUE THREAD

**Issue by tongpu** [argoproj/argo-ui#286]
I've always wondered that the Helm icon in the Argo CD UI looks a bit strange, but today I decided to go down that rabbit hole and found out that this is actually being rendered by custom icon font. This screenshot is from Edge, but it looks similarly bad on all other browser I had available (Chrome and Firefox):

![image](https://user-images.githubusercontent.com/2674075/192767554-1c4bd5b1-7ecd-40be-9090-7ab5ff9026ad.png)

**Comment by agilgur5** [comment]
#287 had a follow-up with #363

Thanks for going down the rabbit hole and fixing this!

**Comment by tongpu** [comment]
> Thanks for going down the rabbit hole and fixing this!

Happy to help. The typography nerd in me was quite happy that I was able to figure it out. :D
