### ISSUE TITLE
[Feature Request] Implement Paging / Async Check for /settings/repos

### ISSUE THREAD

**Issue by kanimaru** [argoproj/argo-ui#487]
Hi,

ArgoCD Team, could you please make the /settings/repos faster?

**Current Problem:**
We have about 50+ Repos connected and everytime we need to visit the page it needs forever to check them all.

**Solution:**
Either implement paging with a search or async checking of the repositories.

Thx in advance.
Sorry found no guidlines how to write a appropirate request :)

Best Regards Kani

**Comment by agilgur5** [comment]
This repo is for shared components between Argo projects, not specific to Argo CD.

Please file an enhancement request in the Argo CD repo instead. Please search the issues there as well, as there is definitely some pagination work ongoing, though I'm not sure if it includes this page.
