### ISSUE TITLE
UI error notification doesn't fit

### ISSUE THREAD

**Issue by JessieTeng89** [argoproj/argo-ui#512]
Describe the bug
Error message popup cannot be displayed properly

To Reproduce

At project level, add new role
Grant "get" to all resources under the related app
Project --> edit --> save
Expected behavior
Error message should be displayed properly, at least all the text should be visible

![image](https://github.com/argoproj/argo-ui/assets/101035990/4785c6a9-dc67-4d04-9a20-fe86654a6d62)

Related to https://github.com/argoproj/argo-cd/issues/16745

**Comment by JessieTeng89** [comment]
I will create a PR to fix it

**Comment by JessieTeng89** [comment]
Hi @agilgur5
I am trying to create a PR for this issue, but got following error message, any idea?
![image](https://github.com/argoproj/argo-ui/assets/101035990/9c0cb330-d5e1-4942-b6f9-598fc4be33a9)

**Comment by agilgur5** [comment]
I've never seen this error before, but here's a GH community discussion on it: https://github.com/orgs/community/discussions/61472

Did you properly fork this repository and create a branch on your fork? I didn't see an `argo-ui` fork in [your public repos](https://github.com/JessieTeng89?tab=repositories)

**Comment by JessieTeng89** [comment]
> I've never seen this error before, but here's a GH community discussion on it: https://github.com/orgs/community/discussions/61472
> 
> Did you properly fork this repository and create a branch on your fork? I didn't see an `argo-ui` fork in [your public repos](https://github.com/JessieTeng89?tab=repositories)

Thanks, I have fixed that issue and I will create a PR soon
