### ISSUE TITLE
Padding error with system level extensions

### ISSUE THREAD

**Issue by Jont828** [argoproj/argo-ui#548]
I'm developing a system level extension and I'm having an issue where there's a `sb-page-wrapper` class that has a padding of 230px that shifts my extension to the left as shown in this picture. I'd like to have my extension be able to use the space right next to the black nav bar on the left.

![image](https://github.com/argoproj/argo-ui/assets/17480384/e1f9ff53-5385-4e6b-8673-5669865e47d6)

There's also another div with style `.cd-layout--extension .cd-layout__content--sb-expanded` that has `padding-left: 230px` as well, which leads me to believe there's a bug where we're accidently applying the padding twice.

![image](https://github.com/argoproj/argo-ui/assets/17480384/bf005462-5ef7-4989-92b1-b2d999a5554a)

**Comment by agilgur5** [comment]
The screenshots look correctly centered, so why do you believe there's a bug?

> with style `.cd-layout--extension .cd-layout__content--sb-expanded`

That sounds specific to Argo CD. This repo is for common UI components between Argo projects and not specific to CD. See also #453
