### ISSUE TITLE
The current tag v2.5.1 is from May 2022

### ISSUE THREAD

**Issue by andrii-korotkov** [argoproj/argo-ui#562]
Hello,
I hope your day is going well.
I’ve noticed that the current tag is more than two years old. I wonder how easy it is to release a new one to be used by other projects. I understand that there may have not been much work on this, but there were still some contributions.
Thanks.

**Comment by andrii-korotkov** [comment]
Answered here https://github.com/argoproj/gitops-engine/issues/584#issuecomment-2160925752

**Comment by agilgur5** [comment]
And here: https://github.com/argoproj/argo-ui/issues/453#issuecomment-2161162335
